version: '3.3'

services:
  pg_denormalized:
    build: services/pg_denormalized
    volumes:
      - .:/mnt/db
      - pg_denormalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
      - POSTGRES_DB=pg_denormalized
    ports:
      - 1047:5432

  pg_normalized:
    build: services/pg_normalized
    volumes:
      - .:/mnt/db
      - pg_normalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
      - POSTGRES_DB=pg_normalized
    ports:
      - 1048:5432

volumes:
    pg_normalized:
    pg_denormalized:
