name: tests_denormalized
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      run: |
        pip3 install -r requirements.txt
    - name: Init submodules and start Docker containers
      run: |
        git submodule init
        git submodule update
        docker compose down -v
        docker volume ls -q --filter name=pg_normalized | xargs -r docker volume rm
        docker volume ls -q --filter name=pg_denormalized | xargs -r docker volume rm
        docker compose up -d --build
        docker ps -a

    - name: Wait for container DNS resolution
      run: |
        echo "Waiting for pg_normalized and pg_denormalized to resolve and initialize..."
        for i in {1..15}; do
          if getent hosts pg_normalized && getent hosts pg_denormalized; then
            echo "Hostnames resolved"
            # Check if databases are ready
            if docker compose exec -T pg_normalized pg_isready -U postgres && docker compose exec -T pg_denormalized pg_isready -U postgres; then
              echo "Databases ready"
              break
            fi
          fi
          echo "Retrying..."
          sleep 3
        done

    - name: Run load_tweets.sh
      run: |
        sh load_tweets.sh
      env:
        CI: "true"
    - name: Debug database status after load
      run: |
        docker compose exec -T pg_normalized psql -U postgres -d pg_normalized -c "SELECT count(*) FROM tweets;"
        docker compose exec -T pg_denormalized psql -U postgres -d pg_denormalized -c "SELECT count(*) FROM tweets_jsonb;"

    - name: Run tests inside pg_denormalized
      run: |
        docker compose exec -e CI=true -T pg_denormalized bash -c "sh /tmp/db/run_tests.sh"
